USE datahaus;

CREATE TABLE details (
_index SERIAL NOT NULL PRIMARY KEY, 
name VARCHAR (15),
address VARCHAR (35),
price INT,
body VARCHAR (450),
subTitle VARCHAR (45),
ff_type CHAR (13),
ff_yearBuilt SMALLINT,
ff_heating CHAR (7), 
ff_cooling CHAR (7), 
ff_parking VARCHAR (10), 
ff_lot VARCHAR (10), 
ff_daysOnZillow VARCHAR(39),
ff_pricePerSqft SMALLINT,
ff_saves SMALLINT,
if_bedRoom SMALLINT,
if_bathRoom VARCHAR (16),
if_heatingAndCooling CHAR (120),
if_basement CHAR (120),
if_flooring SMALLINT,
if_other CHAR (120),
sm_size SMALLINT,
sm_amenities CHAR (120),
sm_spaces VARCHAR (10),
c_typeAndStyle CHAR (120),
c_d_builtIn VARCHAR(39),
c_d_remodel VARCHAR(39),
c_m_roof CHAR (120),
c_m_exterior CHAR (120),
c_other CHAR (120),
ef_l_lot SMALLINT,
ef_l_lotWidth SMALLINT,
ef_other CHAR (120),
parking CHAR (120),
o_l_soldVARCHAR VARCHAR(39),
o_l_soldPrice INT,
a_daysOnZillow VARCHAR(39),
a_pastThirtydayView SMALLINT,
a_savedLog SMALLINT
);