USE datahaus;

CREATE TABLE details_indexed_name (
_index SERIAL NOT NULL PRIMARY KEY, 
name VARCHAR (15),
address VARCHAR (35),
price INT,
body CHAR (500),
subTitle VARCHAR (45),
ff_type CHAR (13),
ff_yearBuilt SMALLINT,
ff_heating CHAR (7), 
ff_cooling CHAR (7), 
ff_parking VARCHAR (10), 
ff_lot VARCHAR (10), 
ff_daysOnZillow CHAR(39),
ff_pricePerSqft SMALLINT,
ff_saves SMALLINT,
if_bedRoom SMALLINT,
if_bathRoom VARCHAR (16),
if_heatingAndCooling CHAR (140),
if_basement CHAR (140),
if_flooring SMALLINT,
if_other CHAR (140),
sm_size SMALLINT,
sm_amenities CHAR (140),
sm_spaces VARCHAR (10),
c_typeAndStyle CHAR (140),
c_builtIn CHAR (39),
c_remodel CHAR (39),
c_roof CHAR (140),
c_exterior CHAR (140),
c_other CHAR (140),
ef_lot SMALLINT,
ef_lotWidth SMALLINT,
ef_other CHAR (140),
parking CHAR (140),
o_soldDate CHAR (39),
o_soldPrice INT,
a_daysOnZillow CHAR (39),
a_pastThirtydayView SMALLINT,
a_savedLog SMALLINT
);

\COPY details_indexed_name (_index,name,address,price,body,subTitle,ff_type,ff_yearBuilt,ff_heating,ff_cooling,ff_parking,ff_lot,ff_daysOnZillow,ff_pricePerSqft,ff_saves,if_bedRoom,if_bathRoom,if_heatingAndCooling,if_basement,if_flooring,if_other,sm_size,sm_amenities,sm_spaces,c_typeAndStyle,c_builtIn,c_remodel,c_roof,c_exterior,c_other,ef_lot,ef_lotWidth,ef_other,parking,o_soldDate,o_soldPrice,a_daysOnZillow,a_pastThirtydayView,a_savedLog) FROM '/Users/tarik/Documents/SDC Project/detailed-part/dataHouz.csv' DELIMITER '|' CSV;
