const faker = require('faker');

const randomize = () => ({
  id: '',
  name: '',
  address: faker.address.streetAddress(),
  price: faker.random.number({ min: 800000, max: 5000000 }),
  body: faker.lorem.paragraph(),
  subTitle: `${faker.address.city()}, ${faker.address.stateAbbr()} ${faker.address.zipCode()}`,
  ff_type: Math.random() > 0.5 ? 'Single Family' : 'Multi-Family',
  ff_yearBuilt: 1918 + Math.floor(Math.random() * 100),
  ff_heating: Math.random() > 0.5 ? 'Central' : 'None',
  ff_cooling: Math.random() > 0.5 ? 'Central' : 'None',
  ff_parking: `${faker.random.number({ min: 1, max: 6 })} spaces`,
  ff_lot: `${faker.random.number({ min: 1000, max: 10000 })} sqft`,
  ff_daysOnZillow: `${faker.date.past()}`,
  ff_pricePerSqft: faker.random.number({ min: 100, max: 1000 }),
  ff_saves: faker.random.number({ min: 70, max: 700 }),
  if_bedRoom: faker.random.number({ min: 1, max: 10 }),
  if_bathRoom: `${faker.random.number({ min: 1, max: 10 })} full, ${faker.random.number({ min: 1, max: 10 })} half`,
  if_heatingAndCooling: faker.random.words(),
  if_basement: faker.random.words(),
  if_flooring: faker.random.number({ min: 1, max: 10 }),
  if_other: faker.random.words(),
  sm_size: faker.random.number({ min: 1, max: 10 }),
  sm_amenities: faker.random.words(),
  sm_spaces: `${faker.random.number({ min: 1, max: 6 })} space`,
  c_typeAndStyle: faker.random.words(),
  c_builtIn: `${faker.date.past()}`,
  c_remodel: `${faker.date.past()}`,
  c_roof: faker.random.words(),
  c_exterior: faker.random.words(),
  c_other: faker.random.words(),
  ef_lot: faker.random.number({ min: 1, max: 10 }),
  ef_lotWidth: faker.random.number({ min: 1, max: 10 }),
  ef_other: faker.random.words(),
  parking: faker.random.words(),
  o_soldDate: `${faker.date.past()}`,
  o_soldPrice: faker.random.number({ min: 800000, max: 5000000 }),
  a_daysOnZillow: `${faker.date.past()}`,
  a_pastThirtydayView: faker.random.number({ min: 5, max: 50 }),
  a_savedLog: faker.random.number({ min: 5, max: 50 }),
});

module.exports = randomize;
